import type { Metadata } from "next";

import "./globals.css";
import RightBar from "./_component/layout/RightBar";
import LeftBar from "./_component/layout/LeftBar";

export const metadata: Metadata = {
  title: "Social media",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className=" min-h-screen flex justify-between max-w-screen-md lg:max-w-screen-lg xl:max-w-screen-xl xxl:max-w-screen-xxl  mx-auto">
          <div className="px-2 xsm:px-4 xxl:px-8">
            <LeftBar />
          </div>
          <div className="flex-1 lg:min-w-[600px] border-x border-borderGrey ">
            {children}
          </div>
          <div className="hidden lg:flex ml-4 md:ml-8 flex-1">
            <RightBar />
          </div>
        </main>
      </body>
    </html>
  );
}
